### ISSUE TITLE
fusion_annotation filter RP5-857K21.7

### ISSUE THREAD

**Issue by jhl667** [ohsu-comp-bio/compbio-galaxy-wrappers#19]
Not in RefSeq.

**Comment by jhl667** [comment]
RP11-1007O24.3 also

**Comment by jhl667** [comment]
RP11-450I1.4

**Comment by jhl667** [comment]
CTA-941F9.9.  Actually, it's looking like we will need to figure out exactly what is showing up in gencode that is not in refseq, and then filter accordingly.  Otherwise, we will need to create gene definitions for all of these gencode genes to send to CGD.

**Comment by patterja** [comment]
I think this issue can be closed. STAR re-indexed using ref_GRCh37.p13_top_level.gff3, which consists of transcripts that already exist in CGD.
