### ISSUE TITLE
Collect tool versions per workflow invocation

### ISSUE THREAD

**Issue by jhl667** [ohsu-comp-bio/compbio-galaxy-wrappers#54]
From CGD Jira:

The request is that we track all versions of all workflow tools in one location, so they can be viewed if necessary.  This could either be done by parsing through version information in each tool, which seems like a large amount of work, or perhaps could be done with the Galaxy API if we were confident the tool versions were all correctly associated with tool wrappers.

**Comment by ok-gitr** [comment]
Issue moved to [Jira](https://service.ohsu.edu/browse/BIO-417).
